#!/usr/bin/env python3
"""
Generate an index.html linking to all HTML files in a directory.
Useful for GitHub Pages hosting of multiple reports.
"""

import os
from pathlib import Path
import argparse

TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.5; }}
        h1 {{ border-bottom: 2px solid #eaeaea; padding-bottom: 0.5rem; }}
        .file-list {{ list-style: none; padding: 0; }}
        .file-item {{ background: #f5f5f5; margin-bottom: 1rem; border-radius: 6px; transition: transform 0.2s; }}
        .file-item:hover {{ transform: translateX(5px); background: #e0e0e0; }}
        .file-link {{ display: block; padding: 1rem; text-decoration: none; color: #333; font-weight: 500; }}
        .file-meta {{ display: block; font-size: 0.85rem; color: #666; margin-top: 0.25rem; font-weight: normal; }}
        footer {{ margin-top: 3rem; border-top: 1px solid #eaeaea; padding-top: 1rem; color: #888; font-size: 0.9rem; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p>Select a report to view:</p>
    
    <ul class="file-list">
        {links}
    </ul>

    <footer>Generated by build_index.py</footer>
</body>
</html>
"""

def main():
    parser = argparse.ArgumentParser(description="Build index.html for a directory of HTML files")
    parser.add_argument("target_dir", nargs="?", default="./item-distributions", help="Directory to scan")
    parser.add_argument("--title", default="TWW Randomizer Item Distributions", help="Page title")
    args = parser.parse_args()
    
    target_dir = Path(args.target_dir)
    files = sorted(target_dir.glob("*.html"))
    
    links = []
    for f in files:
        if f.name == "index.html":
            continue
            
        # Get file stats
        size_kb = f.stat().st_size / 1024
        name = f.stem.replace("_", " ").title()
        
        # Use relative path from index.html location to the file
        relative_path = f.relative_to(Path("."))
        link_html = f"""
        <li class="file-item">
            <a href="{relative_path.as_posix()}" class="file-link">
                {name}
                <span class="file-meta">File: {f.name} • Size: {size_kb:.1f} KB</span>
            </a>
        </li>"""
        links.append(link_html)
    
    output_html = TEMPLATE.format(
        title=args.title,
        links="\n".join(links) if links else "<li>No HTML reports found.</li>"
    )
    
    output_path = Path("./index.html")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output_html)
        
    print(f"Generated {output_path} with {len(links)} links.")

if __name__ == "__main__":
    main()

